config/routes.rb
Rails.application.routes.draw do
  root 'clients#index'
  resources :clients
  resources :intakes

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_one :ClientType
#	accepts_nested_attributes_for :ClientType
end

app/models/client_type.rb
class ClientType < ActiveRecord::Base
	belongs_to :Client
end

app/models/intake.rb
class Intake < ActiveRecord::Base
	has_one :client
	has_one :IntakeType
end

app/models/intake_type.rb
class IntakeType < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
before_action :find_client, only: [:show, :edit, :update, :destroy]
	def index
		@client = Client.all
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		@client.save
		redirect_to @client
	end

	def show
	end
 
	def edit
		@client = Client.find(params[:id])
	end

	def update
		if @client.update(client_params)
			redirect_to @client
		else
			render 'edit'
		end
	end

	def destroy
	end

private

	def client_params
		params.require(:client).permit!
	end

	def find_client
		@client = Client.find(params[:id])
	end
end

app/controllers/intakes_controller.rb
class IntakesController < ApplicationController
before_action :find_intake, only: [:show, :edit, :update, :destroy]
	def index
		@intake = Intake.all
	end
	
	def new
		@intake = Intake.new
	end

	def create
		@intake = Intake.new(intake_params)
		@intake.save
		redirect_to @intake
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end



private
	def intake_params
		params.require(:intake).permit!
	end
	
	def find_intake
		@intake = Intake.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/intake_helper.rb
module IntakeHelper
end

app/views/clients/_form.html.haml
.panel-body
	= simple_form_for @client do |f|
		.col-md-5
			= f.input :name, :autofocus => true, class: 'form-control'
			= f.input :short_name, :label => "Short Name"
			= f.input :office_contact
			= f.input :address
			= f.input :phone
			= f.input :clienttype_id, :collection => ClientType.all, include_blank: false
		.col-md-5
			= f.input :notes
			= f.button :submit

app/views/clients/edit.html.haml
%h1 Edit Client

= render 'form'

app/views/clients/index.html.haml
.panel.panel-primary
	.panel-heading Client List
	%table.table.table-bordered
		%tr
			%th Name
			%th Info
			%th Address
		- @client.each do |c|
			%tr
				%td= link_to c.name, c
				%td= c.short_name
				%td= c.address
=link_to 'New Client', new_client_path, class: "btn btn-sm btn-primary"

app/views/clients/new.html.haml
%h1 New Client Form
= render 'form'

app/views/clients/show.html.haml
.main_content
	.row
		.col-md-4
			%h2= @client.name
			%hr
			%h5= "Phone: #{@client.phone}"
			%h5= "Fax: #{@client.fax}"
			%h5= "Address: #{@client.address}"
			%h5= "Office Contact: #{@client.office_contact}"
	.row
		.col-md-6
		Notes:
		= @client.notes
	.row
		.col-md-1
		= link_to 'Edit Client', edit_client_path, class: "btn btn-sm btn-primary"

app/views/intakes/_form.html.haml
.panel-body
	= simple_form_for @intake do |f|
		.col-md-4
			= f.input :rcvd_date, as: :string, input_html: {type: :date}
			= f.input :post_date, as: :string, input_html: {type: :date}
			= f.input :pgs
		.col-md-4
			= f.input :scan_date, as: :string, input_html: {type: :date}
			= f.input :service_date, as: :string, input_html: {type: :date}
			= f.input :client_id, :collection => Client.all, include_blank: false
			= f.input :intaketype_id, :collection => IntakeType.all, include_blank: false
		.col-md-4
			= f.input :notes 
			= f.button :submit

app/views/intakes/index.html.haml
.panel.panel-primary
	.panel-heading Intake Batch List
	%table.table.table-bordered
		%tr
			%th Name
			%th Info
			%th Address
		- @intake.each do |c|
			%tr
				%td= link_to c.id, c
				%td= c.service_date
				%td= c.rcvd_date
=link_to 'New Batch', new_intake_path, class: "btn btn-sm btn-primary"

app/views/intakes/new.html.haml
.panel.panel-primary
	.panel-heading Intake Form
	= render 'form'

app/views/intakes/show.html.haml
.panel.panel-primary
	.panel-heading Intake Batch
	.panel-body
		= @intake.rcvd_date

app/views/layouts/application.html.haml
!!!
%html
%head
  %title HiveMind
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
.container
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} HiveMind
      #navbar.navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li= link_to "Intake", intakes_path
          %li= link_to "Charges", root_path
          %li= link_to "Coding", root_path
          %li= link_to "Payments", root_path
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Lists
              %span.caret
            %ul.dropdown-menu
              %li= link_to "Clients", clients_path
              %li= link_to "Projects", root_path
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "../navbar-static-top/"} Info
  %br
  =yield